name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTS=ON -DBUILD_SHARED=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Run tests
        run: ctest --test-dir build -V
