name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Ninja
        run: choco install ninja
      - name: Configure
        run: cmake -S . -B build -G Ninja -DBUILD_TESTS=ON -DBUILD_SHARED=OFF
      - name: Build
        run: cmake --build build --parallel
      - name: Run tests
        run: ctest --test-dir build -V
