name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ make
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTS=ON -DBUILD_SHARED=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Run tests
        run: ctest --test-dir build -V

  macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies
        run: brew install cmake
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTS=ON -DBUILD_SHARED=ON
      - name: Build
        run: cmake --build build --parallel
      - name: Run tests
        run: ctest --test-dir build -V

  windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTS=ON -DBUILD_SHARED=ON -DCMAKE_BUILD_TYPE=Release
      - name: Build (Release)
        run: cmake --build build --parallel --config Release
      - name: Run tests (Release)
        run: ctest --test-dir build -V -C Release
